# Generated by Django 5.1.2 on 2024-11-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Planejando', 'Planejando'), ('Ativo', 'Ativo'), ('Cancelado', 'Cancelado')], default='Planejando', max_length=10)),
            ],
        ),
    ]
